### ISSUE TITLE
Problem importing Linguistica:   ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by melindaloubser1** [linguistica-uchicago/lxa5#15]
![image](https://user-images.githubusercontent.com/32034278/30524087-55982b10-9bed-11e7-81c9-9c882cfa9162.png)
Hi,
I have installed Linguistica 5.2.0 which is the version automatically installed with pip on Python 3.6.0, but get the error above when trying to import it. As can be seen on the screenshot, the versions of the various required libraries are all correct, but upon import it says, "RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa". I've tried different different versions of numpy (1.11.3 - could not install - 1.13.0 - gave a different version error) which did not resolve the problem. Any advice on getting this going?

**Comment by jacksonllee** [comment]
Hi, my googling suggests that this issue is not too uncommon for other libraries using numpy, especially if there are multiple versions of numpy installed on your system (see [this StackOverflow thread](https://stackoverflow.com/questions/28517937/how-can-i-upgrade-numpy), for instance).  I don't have a Windows machine laying around to test things out, but I'd suggest trying to install the most up-to-date version of numpy and see if that solves the problem:

```
$ pip install --upgrade numpy
```

If this command doesn't work, I'd then try to use `python3 -m` to make sure it's trying to upgrade numpy for the specific Python interpreter you want:

```
$ python3 -m pip install --upgrade numpy
```

I hope this helps!

**Comment by melindaloubser1** [comment]
Hi, thanks for the feedback - I tried the step you suggested (also found them on google), but that did not work; it returned an error about unsupported numpy build.  I uninstalled python in the end and installed WinPython, plus the numpy+mkl library (mkl not included in distribution). Not sure if mkl portion was causing the problem in the first place? It now imports without error messages.
